// File generated by the BNF Converter (bnfc 2.9.3).

package javalette.Absyn;

public class BreR  extends Bre {
  public final Expr expr_;
  public int line_num, col_num, offset;
  public BreR(Expr p1) { expr_ = p1; }

  public <R,A> R accept(javalette.Absyn.Bre.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.BreR) {
      javalette.Absyn.BreR x = (javalette.Absyn.BreR)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
