// File generated by the BNF Converter (bnfc 2.9.3).

package javalette.Absyn;

public class EArray  extends Expr {
  public final Expr expr_;
  public final ListBre listbre_;
  public int line_num, col_num, offset;
  public EArray(Expr p1, ListBre p2) { expr_ = p1; listbre_ = p2; }

  public <R,A> R accept(javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.EArray) {
      javalette.Absyn.EArray x = (javalette.Absyn.EArray)o;
      return this.expr_.equals(x.expr_) && this.listbre_.equals(x.listbre_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.listbre_.hashCode();
  }


}
