// File generated by the BNF Converter (bnfc 2.9.3).

package javalette.Absyn;

public abstract class TypeBase implements java.io.Serializable {
  public abstract <R,A> R accept(TypeBase.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(javalette.Absyn.Int p, A arg);
    public R visit(javalette.Absyn.Doub p, A arg);
    public R visit(javalette.Absyn.Bool p, A arg);
    public R visit(javalette.Absyn.Void p, A arg);
    public R visit(javalette.Absyn.Ptr p, A arg);

  }

}
