// File generated by the BNF Converter (bnfc 2.9.3).

package javalette.Absyn;

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(javalette.Absyn.Base p, A arg);
    public R visit(javalette.Absyn.Array p, A arg);
    public R visit(javalette.Absyn.Fun p, A arg);

  }

}
