// File generated by the BNF Converter (bnfc 2.9.3).

package javalette.Absyn;

public class Array  extends Type {
  public final TypeBase typebase_;
  public final ListBr listbr_;
  public int line_num, col_num, offset;
  public Array(TypeBase p1, ListBr p2) { typebase_ = p1; listbr_ = p2; }

  public <R,A> R accept(javalette.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.Array) {
      javalette.Absyn.Array x = (javalette.Absyn.Array)o;
      return this.typebase_.equals(x.typebase_) && this.listbr_.equals(x.listbr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.typebase_.hashCode())+this.listbr_.hashCode();
  }


}
