// File generated by the BNF Converter (bnfc 2.9.3).

package javalette.Absyn;

public class BrR  extends Br {
  public int line_num, col_num, offset;
  public BrR() { }

  public <R,A> R accept(javalette.Absyn.Br.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.BrR) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
