// File generated by the BNF Converter (bnfc 2.9.3).

package javalette.Absyn;

public class EArrayInit  extends Expr {
  public final TypeBase typebase_;
  public final ListBre listbre_;
  public int line_num, col_num, offset;
  public EArrayInit(TypeBase p1, ListBre p2) { typebase_ = p1; listbre_ = p2; }

  public <R,A> R accept(javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.EArrayInit) {
      javalette.Absyn.EArrayInit x = (javalette.Absyn.EArrayInit)o;
      return this.typebase_.equals(x.typebase_) && this.listbre_.equals(x.listbre_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.typebase_.hashCode())+this.listbre_.hashCode();
  }


}
