// -*- Java -*- File generated by the BNF Converter (bnfc 2.9.3).
// Lexer definition for use with JLex
package javalette;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  final int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yycolumn = unknown - 1;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return new ComplexSymbolFactory.Location(yyline+1, yycolumn+1, yychar);
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return new ComplexSymbolFactory.Location(left.getLine(), left.getColumn()+yylength(), left.getOffset()+yylength());
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yychar;
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yychar = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		82,
		84,
		84,
		84,
		86,
		88
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yychar = yychar
			+ yy_buffer_index - yy_buffer_start;
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NOT_ACCEPT,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NOT_ACCEPT,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NOT_ACCEPT,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NOT_ACCEPT,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NOT_ACCEPT,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NOT_ACCEPT,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NOT_ACCEPT,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NO_ANCHOR,
		/* 132 */ YY_NO_ANCHOR,
		/* 133 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"43:9,51,44,43,51,42,43:18,51,14,45,41,43,18,15,50,1,2,7,9,3,10,13,17,47:10," +
"11,6,19,8,12,43:2,48:26,20,46,21,43,50,43,26,22,36,28,25,31,49,40,33,49:2,2" +
"4,49,27,23,38,49,32,30,34,29,39,35,49,37,49,4,16,5,43:66,48:23,43,48:7,49:2" +
"4,43,49:8,43:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,134,
"0,1:8,2,3,4,1,5,1,6,7,8,1,9,10,1,11,12,1:2,13,1:9,14,1:2,15:4,16,15:11,1:4," +
"17,1:7,18,1:2,19,20,21,22,23,1:2,24,1,25,22,26,27,28,29,30,31,32,33,34,35,3" +
"6,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,6" +
"1,62,63,64,65,66,67,68,69,70,71,72,73,74,75,15,76,15")[0];

	private int yy_nxt[][] = unpackFromString(77,52,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,71,17,18,19,20,21,22,133:2,111,133,9" +
"8,127,133,128,99,129,72,112,121,133:3,113,133,23,24,78,24,25,78,26,133:2,78" +
",24,-1:60,27,-1:52,28,-1:52,29,-1,30,-1:47,31,-1:51,32,-1:58,33,-1:43,35,-1" +
":9,36,-1:42,37,-1:64,38,-1:52,133,130,133:17,-1:6,131:2,133,131,-1:2,23:43," +
"-1,23:7,-1:13,70,-1:33,26,-1:5,36:43,-1,36:7,-1:22,133:19,-1:6,131:2,133,13" +
"1,-1:26,77,-1:21,43,-1:48,75,-1:51,76,-1:54,43,-1:20,34,-1:57,133:5,83,133:" +
"3,39,133:9,-1:6,131:2,133,131,-1:48,73,-1:21,57,-1:44,80,-1:36,73,-1:26,133" +
":13,40,133:5,-1:6,131:2,133,131,-1:23,133:10,41,133:8,-1:6,131:2,133,131,-1" +
",1,55:6,74,55:34,-1,55,56,55:7,-1:22,133:12,42,133:6,-1:6,131:2,133,131,-1," +
"1,78:41,-1,78,-1,78:7,-1:22,133:3,44,133:15,-1:6,131:2,133,131,-1,1,58:41,5" +
"9,58,75,60,61,58:5,-1:22,133:2,45,133:16,-1:6,131:2,133,131,-1,1,62:26,63,6" +
"2:3,64,65,62,66,62:7,67,62,76,68,69,62:5,-1:22,133:3,46,133:15,-1:6,131:2,1" +
"33,131,-1:23,133:6,47,133:12,-1:6,131:2,133,131,-1:23,133:3,48,133:15,-1:6," +
"131:2,133,131,-1:23,133:3,49,133:15,-1:6,131:2,133,131,-1:23,133:3,50,133:1" +
"5,-1:6,131:2,133,131,-1:23,133:12,51,133:6,-1:6,131:2,133,131,-1:23,133:5,5" +
"2,133:13,-1:6,131:2,133,131,-1:23,133:5,53,133:13,-1:6,131:2,133,131,-1:23," +
"133:9,54,133:9,-1:6,131:2,133,131,-1:23,133:3,79,133:3,101,133:11,-1:6,131:" +
"2,133,131,-1:23,133,81,133:2,114,133:14,-1:6,131:2,133,131,-1:23,133:8,85,1" +
"33:10,-1:6,131:2,133,131,-1:23,133:2,87,133:16,-1:6,131:2,133,131,-1:23,133" +
":7,89,133:11,-1:6,131:2,133,131,-1:23,133:11,90,133:7,-1:6,131:2,133,131,-1" +
":23,133:8,91,133:10,-1:6,131:2,133,131,-1:23,133:2,92,133:16,-1:6,131:2,133" +
",131,-1:23,133:2,93,133:16,-1:6,131:2,133,131,-1:23,133:14,94,133:4,-1:6,13" +
"1:2,133,131,-1:23,133:10,95,133:8,-1:6,131:2,133,131,-1:23,133:4,96,133:14," +
"-1:6,131:2,133,131,-1:23,133:3,97,133:15,-1:6,131:2,133,131,-1:23,133:2,100" +
",133:16,-1:6,131:2,133,131,-1:23,133:10,102,133:4,132,133:3,-1:6,131:2,133," +
"131,-1:23,133,103,133:17,-1:6,131:2,133,131,-1:23,133:2,104,133:16,-1:6,131" +
":2,133,131,-1:23,133:11,105,133:7,-1:6,131:2,133,131,-1:23,106,133:18,-1:6," +
"131:2,133,131,-1:23,133:7,107,133:11,-1:6,131:2,133,131,-1:23,133:7,108,133" +
":11,-1:6,131:2,133,131,-1:23,133:3,109,133:15,-1:6,131:2,133,131,-1:23,133:" +
"6,110,133:12,-1:6,131:2,133,131,-1:23,133:18,115,-1:6,131:2,133,131,-1:23,1" +
"33:7,116,133:11,-1:6,131:2,133,131,-1:23,133:10,117,133:8,-1:6,131:2,133,13" +
"1,-1:23,133:12,118,133:6,-1:6,131:2,133,131,-1:23,133:2,119,133:16,-1:6,131" +
":2,133,131,-1:23,133:3,120,133:15,-1:6,131:2,133,131,-1:23,133,122,133:17,-" +
"1:6,131:2,133,131,-1:23,133:12,123,133:6,-1:6,131:2,133,131,-1:23,133:3,124" +
",133:15,-1:6,131:2,133,131,-1:23,133,125,133:17,-1:6,131:2,133,131,-1:23,13" +
"3:16,126,133:2,-1:6,131:2,133,131,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", sym._SYMB_0, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", sym._SYMB_3, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", sym._SYMB_4, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", sym._SYMB_5, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", sym._SYMB_6, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ return cf.newSymbol("", sym._SYMB_7, left_loc(), right_loc()); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", sym._SYMB_17, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ return cf.newSymbol("", sym._SYMB_13, left_loc(), right_loc()); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", sym._SYMB_10, left_loc(), right_loc()); }
					case -13:
						break;
					case 13:
						{ return cf.newSymbol("", sym._SYMB_22, left_loc(), right_loc()); }
					case -14:
						break;
					case 14:
						{ return cf.newSymbol("", sym._SYMB_12, left_loc(), right_loc()); }
					case -15:
						break;
					case 15:
						{ return cf.newSymbol("", sym._SYMB_14, left_loc(), right_loc()); }
					case -16:
						break;
					case 16:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", sym._SYMB_18, left_loc(), right_loc()); }
					case -18:
						break;
					case 18:
						{ return cf.newSymbol("", sym._SYMB_19, left_loc(), right_loc()); }
					case -19:
						break;
					case 19:
						{ return cf.newSymbol("", sym._SYMB_20, left_loc(), right_loc()); }
					case -20:
						break;
					case 20:
						{ return cf.newSymbol("", sym._SYMB_27, left_loc(), right_loc()); }
					case -21:
						break;
					case 21:
						{ return cf.newSymbol("", sym._SYMB_28, left_loc(), right_loc()); }
					case -22:
						break;
					case 22:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -23:
						break;
					case 23:
						{ /* skip */ }
					case -24:
						break;
					case 24:
						{ /* ignore white space. */ }
					case -25:
						break;
					case 25:
						{ left = left_loc(); yybegin(STRING); }
					case -26:
						break;
					case 26:
						{ return cf.newSymbol("", sym._INTEGER_, left_loc(), right_loc(), new Integer(yytext())); }
					case -27:
						break;
					case 27:
						{ return cf.newSymbol("", sym._SYMB_24, left_loc(), right_loc()); }
					case -28:
						break;
					case 28:
						{ return cf.newSymbol("", sym._SYMB_8, left_loc(), right_loc()); }
					case -29:
						break;
					case 29:
						{ return cf.newSymbol("", sym._SYMB_9, left_loc(), right_loc()); }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", sym._SYMB_11, left_loc(), right_loc()); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", sym._SYMB_23, left_loc(), right_loc()); }
					case -32:
						break;
					case 32:
						{ return cf.newSymbol("", sym._SYMB_25, left_loc(), right_loc()); }
					case -33:
						break;
					case 33:
						{ return cf.newSymbol("", sym._SYMB_15, left_loc(), right_loc()); }
					case -34:
						break;
					case 34:
						{ return cf.newSymbol("", sym._SYMB_16, left_loc(), right_loc()); }
					case -35:
						break;
					case 35:
						{ yybegin(COMMENT); }
					case -36:
						break;
					case 36:
						{ /* skip */ }
					case -37:
						break;
					case 37:
						{ return cf.newSymbol("", sym._SYMB_21, left_loc(), right_loc()); }
					case -38:
						break;
					case 38:
						{ return cf.newSymbol("", sym._SYMB_26, left_loc(), right_loc()); }
					case -39:
						break;
					case 39:
						{ return cf.newSymbol("", sym._SYMB_34, left_loc(), right_loc()); }
					case -40:
						break;
					case 40:
						{ return cf.newSymbol("", sym._SYMB_36, left_loc(), right_loc()); }
					case -41:
						break;
					case 41:
						{ return cf.newSymbol("", sym._SYMB_33, left_loc(), right_loc()); }
					case -42:
						break;
					case 42:
						{ return cf.newSymbol("", sym._SYMB_35, left_loc(), right_loc()); }
					case -43:
						break;
					case 43:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), new Double(yytext())); }
					case -44:
						break;
					case 44:
						{ return cf.newSymbol("", sym._SYMB_31, left_loc(), right_loc()); }
					case -45:
						break;
					case 45:
						{ return cf.newSymbol("", sym._SYMB_37, left_loc(), right_loc()); }
					case -46:
						break;
					case 46:
						{ return cf.newSymbol("", sym._SYMB_40, left_loc(), right_loc()); }
					case -47:
						break;
					case 47:
						{ return cf.newSymbol("", sym._SYMB_42, left_loc(), right_loc()); }
					case -48:
						break;
					case 48:
						{ return cf.newSymbol("", sym._SYMB_32, left_loc(), right_loc()); }
					case -49:
						break;
					case 49:
						{ return cf.newSymbol("", sym._SYMB_43, left_loc(), right_loc()); }
					case -50:
						break;
					case 50:
						{ return cf.newSymbol("", sym._SYMB_30, left_loc(), right_loc()); }
					case -51:
						break;
					case 51:
						{ return cf.newSymbol("", sym._SYMB_39, left_loc(), right_loc()); }
					case -52:
						break;
					case 52:
						{ return cf.newSymbol("", sym._SYMB_38, left_loc(), right_loc()); }
					case -53:
						break;
					case 53:
						{ return cf.newSymbol("", sym._SYMB_29, left_loc(), right_loc()); }
					case -54:
						break;
					case 54:
						{ return cf.newSymbol("", sym._SYMB_41, left_loc(), right_loc()); }
					case -55:
						break;
					case 55:
						{ /* skip */ }
					case -56:
						break;
					case 56:
						{ /* skip */ }
					case -57:
						break;
					case 57:
						{ yybegin(YYINITIAL); }
					case -58:
						break;
					case 58:
						{ pstring += yytext(); }
					case -59:
						break;
					case 59:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -60:
						break;
					case 60:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return cf.newSymbol("", sym._STRING_, left, right_loc(), foo.intern()); }
					case -61:
						break;
					case 61:
						{ yybegin(ESCAPED); }
					case -62:
						break;
					case 62:
						{ pstring += yytext(); yybegin(STRING); }
					case -63:
						break;
					case 63:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -64:
						break;
					case 64:
						{ pstring += "\f"; yybegin(STRING); }
					case -65:
						break;
					case 65:
						{ pstring += "\r"; yybegin(STRING); }
					case -66:
						break;
					case 66:
						{ pstring += "\t"; yybegin(STRING); }
					case -67:
						break;
					case 67:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -68:
						break;
					case 68:
						{ pstring += "\""; yybegin(STRING); }
					case -69:
						break;
					case 69:
						{ pstring += "\\"; yybegin(STRING); }
					case -70:
						break;
					case 71:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -71:
						break;
					case 72:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -72:
						break;
					case 73:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), new Double(yytext())); }
					case -73:
						break;
					case 74:
						{ /* skip */ }
					case -74:
						break;
					case 75:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -75:
						break;
					case 76:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -76:
						break;
					case 78:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -77:
						break;
					case 79:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -78:
						break;
					case 81:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -79:
						break;
					case 83:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -80:
						break;
					case 85:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -81:
						break;
					case 87:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -82:
						break;
					case 89:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -83:
						break;
					case 90:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -84:
						break;
					case 91:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -85:
						break;
					case 92:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -86:
						break;
					case 93:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -87:
						break;
					case 94:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -88:
						break;
					case 95:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -89:
						break;
					case 96:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -90:
						break;
					case 97:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -91:
						break;
					case 98:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -92:
						break;
					case 99:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -93:
						break;
					case 100:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -94:
						break;
					case 101:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -95:
						break;
					case 102:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -96:
						break;
					case 103:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -97:
						break;
					case 104:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -98:
						break;
					case 105:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -99:
						break;
					case 106:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -100:
						break;
					case 107:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -101:
						break;
					case 108:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -102:
						break;
					case 109:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -103:
						break;
					case 110:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -104:
						break;
					case 111:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -105:
						break;
					case 112:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -106:
						break;
					case 113:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -107:
						break;
					case 114:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -108:
						break;
					case 115:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -109:
						break;
					case 116:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -110:
						break;
					case 117:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -111:
						break;
					case 118:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -112:
						break;
					case 119:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -113:
						break;
					case 120:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -114:
						break;
					case 121:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -115:
						break;
					case 122:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -116:
						break;
					case 123:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -117:
						break;
					case 124:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -118:
						break;
					case 125:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -119:
						break;
					case 126:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -120:
						break;
					case 127:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -121:
						break;
					case 128:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -122:
						break;
					case 129:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -123:
						break;
					case 130:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -124:
						break;
					case 131:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -125:
						break;
					case 132:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -126:
						break;
					case 133:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -127:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
